version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # Default port
      - "4571:4571" # Alternate port for S3
    environment:
      - SERVICES=iam,lambda,s3,dynamodb,events,apigateway,cloudwatch
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker

    volumes:
      - "./localstack-data:/tmp/local-stack"
      - "/var/run/docker.sock:/var/run/docker.sock"
